### ISSUE TITLE
Should there be two percent(%) signs when showing percentage? 

### ISSUE THREAD

**Issue by softinio** [justinhj/battery.nvim#9] opened 2022-08-21 19:18 UTC
Should there be two percent(%) signs when showing percentage? 

[Here](https://github.com/justinhj/battery.nvim/blob/main/lua/battery/battery.lua#L178)

**Comment by justinhj** [comment] 2022-09-14 05:48
I'm only seeing one, could you share your config and platform?

**Comment by softinio** [comment] 2022-09-17 18:00
Hello Sir, Hope you are well.

I am using neovim and this plugin on MacOS Moneterey via Nix.

Watch this: https://shared.softinio.com/Screen-Recording-2022-09-17-10-55-03.mp4

My Neovim Config: https://git.softinio.com/softinio/nix-config/src/branch/main/programs/neovim/init.lua#L76-L85

Any questions let me know. Thanks!

**Comment by justinhj** [comment] 2022-09-19 20:34
Thanks for the info. Still can't repro. I'm also on Monterey. Not sure if Nix makes any difference. Maybe it's a bug depending on terminal. I'm using Kitty and have verified also in Terminal. 
Something subtle going on.

**Comment by justinhj** [comment] 2022-09-20 05:12
Confirmed the difference is between handling strings in lualine vs galaxyline. If I only use % in the status line string then it causes errors in lualine (and staline), but galaxyline shows it fine. Will try to find out the cause and a work around.

**Comment by justinhj** [comment] 2022-09-20 17:38
Based on some guesswork since I don't see it documented in Galaxyline, it treats strings as already formatted, so % control codes are ignored. Since I don't want to break support for lualine there are two options: Provide a config option that formats the status line string before returning, or (preferred) modify the instructions for galaxyline to preformat the string manually.

```
gls.right[4] = {
	BatteryNvim = {
		provider = function()
			local status = require("battery").get_status_line()
			local formatted = string.format(status)
			return formatted
		end,
		separator = "",
		separator_highlight = { colors.bg, colors.purple },
		highlight = { colors.grey, colors.purple },
	},
```

@softinio if this works for you I will edit the documentation and close the issue.

**Comment by justinhj** [comment] 2022-09-21 20:54
Have updated the docs to reflect the above, let me know if it works for you @softinio and I will close the issue

**Comment by softinio** [comment] 2022-09-22 03:22
@justinhj Thank you for spending the time on this. Awesome troubleshooting/debugging 👏

Yup this was the issue and resolved my issue. Your documentation perfect , followed it and all good now.

Updated my config with what you suggested here for reference: https://git.softinio.com/softinio/nix-config/pulls/10/files

Result: 

![battery2](https://user-images.githubusercontent.com/3371635/191651255-a96f1a00-2b37-4647-83d7-420718b16d1a.png)

**Closed** 2022-09-24 03:45 UTC
